services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io@sha256:2989ddbb53049783642c9e4f86dd934c3f659b91b512e588a4d4fd013ff0501e
    container_name: changedetection
    environment:
      - TZ=Asia/Kathmandu
    volumes:
      - ./config:/config:z
    ports:
      - 5000:5000
    restart: unless-stopped
