services:
  jellyfin:
    image: jellyfin/jellyfin@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
    container_name: jellyfin
    volumes:
      - ./data/config:/config:z
      - ./data/cache:/cache:z
      - /media/anime:/anime:z
      - /media/movies:/movies:z
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: "unless-stopped"
    ports:
      - 8096:8096
    networks:
      - media_network

networks:
  media_network:
    external: true
