services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kathmandu
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - media_network

  prowlarr:
    depends_on:
      - flaresolverr
    image: lscr.io/linuxserver/prowlarr@sha256:e74a1e093dcc223d671d4b7061e2b4946f1989a4d3059654ff4e623b731c9134
    container_name: prowlarr
    environment:
      - TZ=Asia/Kathmandu
    volumes:
      - ./data/prowlarr:/config:z
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media_network

  downloader:
    container_name: downloader
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=5.1.4-2
      - QBT_WEBUI_PORT=8080
      - TZ=Asia/Kathmandu
    image: qbittorrentofficial/qbittorrent-nox@sha256:85fe2690f418dabffc4907276b3cdffcb7880c7114157b32f932d3b97bac45af
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ./data/downloader:/config:z
      - /media/downloads:/downloads:z
    restart: unless-stopped
    networks:
      - media_network

  radarr:
    depends_on:
      - downloader
    image: lscr.io/linuxserver/radarr@sha256:6d3e68474ea146f995af98d3fb2cb1a14e2e4457ddaf035aa5426889e2f9249c
    container_name: radarr
    environment:
      - TZ=Asia/Kathmandu
    volumes:
      - ./data/radarr:/config:z
      - /media/movies:/movies:z
      - /media/downloads:/downloads:z
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media_network

  sonarr:
    depends_on:
      - downloader
    image: lscr.io/linuxserver/sonarr@sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1
    container_name: sonarr
    environment:
      - TZ=Asia/Kathmandu
    volumes:
      - ./data/sonarr:/config:z
      - /media/anime:/series:z
      - /media/downloads:/downloads:z
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
